 CREATE TABLE IF NOT EXISTS users(
  id int NOT NULL,
  group_id int NOT NULL,
  username varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  mobile varchar(20) NOT NULL,
  dob date DEFAULT NULL,
  sex varchar(10) NOT NULL DEFAULT 'M',
  password varchar(100) NOT NULL,
  raw_password varchar(100) DEFAULT NULL,
  pass_reset_code varchar(32) DEFAULT NULL,
  reset_code_time timestamp DEFAULT NULL,
  login_try smallint NOT NULL DEFAULT 0,
  last_login timestamp DEFAULT NULL,
  ip varchar(40) NOT NULL,
  address text DEFAULT NULL,
  preference text DEFAULT NULL,
  user_image varchar(250) DEFAULT NULL,
  created_at timestamp DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL
); 